### ISSUE TITLE
🐛 Errors getting lost when accessing invalid external task payload

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#216]
#### Describe your issue

If an error occurs while evaluating an external task's payload, the occurred error gets lost.

#### How can others reproduce the issue?

Create a process with external task and try to access an undefined property in token. 

#### Possible solution

Catch all errors and write them to the log.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@roblen45  What exactly do you mean by "gets lost"? 
Is it not persisted at all, when `handleSystemError` is called, or is some info missing from the error, or does it not get returned to the external ServiceTask?

**Comment by ElRaptorus** [comment]
After conferring with @roblen45, I think this is an issue with the FlowNodeHandlers for ExternalService tasks. 

The handler uses a function to determine the payload to store with an external task. If that function fails, the ProcessEngine seems to just freeze.
This is most likely due to a missing Try/Catch in [this handler function](https://github.com/process-engine/process_engine_core/blob/develop/src/runtime/engine/flow_node_handler/service_task_handlers/external_service_task_handler.ts#L188).

What needs to happen here is:
- Wrap the code block in the aforementioned method in a Try/Catch
- When an error occurs, set the FlowNodeInstances state to `error`
- Throw the error

@alexanderkasten @SteffenKn Perhaps you can take care of this, with this additional info?
