### ISSUE TITLE
🐛 timer expressions with token access doesn't work anymore

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#249]
#### Describe your issue

The validation of timer expression doesn't allow accessing the token.

Before changing the validation it was possible to define timer expressions like this:

`PT${token.history.rezeptEingeben.form_fields.eiweissrastDauer}M`

The result of evaluating that expression is a valid ISO8601 format.

But you get the following error:

The given duration definition `PT${token.history.rezeptEingeben.form_fields.eiweissrastDauer}M` is not in ISO8601 format

#### How can others reproduce the issue?

Deploy bier_brauen.bpmn of dog_food_klub repro.

#### Possible solution

Allow timer expressions with token access.

Please ensure that with an integration test!

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@roblen45 @robpal94
Since the ModelParser cannot know any token-related context, I'd just remove that timer validation from the model parser altogether and place it in the TimerFacade.
The facade can then perform the validation, after the content was retrieved from the token.
This way we have security in terms of token context and can be sure that timers are correctly validated for any type of event (StartEvent, Intermediate- & Boundary Events).
