### ISSUE TITLE
🐛 Storage Configuration for SQLite Databases is ignored

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#286]
#### Describe your issue

Its possible to set a custom database name in the sqlite config. However, the options are never applied. 

I wanted the runtime to create only one database for every table and set the `storage` parameter of all repositories to `database.sqlite`. However, the runtime creates distinct Databases for every defined repository.

#### How can others reproduce the issue?

First, delete your datastore in `~/Library/Application Support/process_engine_runtime/databases`

In `config/sqlite/process_engine`
* Change every `storage` parameter to `database.sqlite`
* Start the runtime
* Check the folder mentioned above,
* See, that the runtime still creates distinct databases for each repository.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@robpal94 You are correct.

This is a bug with the migrations.
They use the wrong storage name for their configs.

This must be corrected here:
https://github.com/process-engine/process_engine_runtime/blob/develop/src/migrator.ts#L39

I think the best approach to this would be to find a way to get the migrator to load the already existing config files, rather than having it cobble together its own configs.

You can extract the necessary config path through the `CONFIG_PATH` and `NODE_ENV` variables.

**Comment by ElRaptorus** [comment]
As this is somewhat critical, I'm going to include a fix for this with the release.

**Comment by ElRaptorus** [comment]
Fixed in Release v7.1.0.
