### ISSUE TITLE
✨ Pass Token Through Manual Tasks

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#324]
#### Describe your issue

If you use a Manual Task in your process, the token after the Manual Task Finished will always be empty.

If you try to confirm the deletion of an entity you have no clue on which entity you confirmed the deletion after the Manual Task since the token is empty.

#### How can others reproduce the issue?

For easy reproducibility I made this diagram:
[manual task error.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3121645/manual.task.error.bpmn.zip)

Just run it in BPMN-Studio and check the token. 

#### Possible solution

Pass the token through the Manual Task.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Out of curiosity, why can't you just use `token.history.yourtasknamehere` to get whatever token results you need?

ManualTasks return empty tokens by design. After all, they don't do anything that could even produce any kind of result. 
Attaching the results from other tasks to a ManualTasks sounds like a bad idea, because the resulting token would imply that the ManualTask actually performed some kind of operation, when in fact it never has.

I'll discuss this with @rrrene but off hand I'm against this idea.
