### ISSUE TITLE
🐛 Incorrect token history for FlowNodes with multiple FlowNodeInstances

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#354]
## Process

<img width="919" alt="Bildschirmfoto 2019-06-13 um 16 09 50" src="https://user-images.githubusercontent.com/17248802/59439506-b1bd7c00-8df5-11e9-9cb2-2b153c35ae36.png">

[token history.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3286549/token.history.bpmn.zip)

## Description

*Current Behavior:*

There is a UserTask in a loop. So there is the possibility that this UserTask gets displayed more than one time.

The first time the call for the token history of that task will be correct:
`token.history['user-task']`
This will return the estimated result of that UserTask.

However if you run through that task a second time the token history will not be updated correctly.
The second time (and all other times after that) the token history will always return the result of the FIRST execution.

*Expected Behavior:*

Every time you call the token history of a task it should return the last result of that task not the first.

Or the other way would be returning ALL results of all executions of that task.

**Comment by ElRaptorus** [comment]
This is going to be tricky to solve. 

The problem here is that the generated token history is essentially a plain `json` object, with keys for each FlowNode that has made an entry in the history.

Basically, it looks like this:

```json
{
  "StartEvent1": {"some": "thing"},
  "UserTask1": {},
  "EndEvent1": "insertsomethinghere",
}
```

The problem here is obvious: 
We can't assign multiple results for the same key. Something will always be overwritten.

Now, we *could* circumvent this problem, by storing them in an Array, like so: 

```json
{
  "UserTask1": [{ 
      "result1": "value"
    }, {
      "result2": "value"
  }]
}
```

However, this will break the `token.history.FlowNodeId.someproperty` semantic, which is potentially going to break a **lot** of ProcessModels.

There is also the question on how to allow a user to differentiate between the various results. The only really unique identifier we have for each is the `FlowNodeInstanceId`, but I'm not sure that this will be enough for a user to recognize which result belongs to which execution.

I'm going to discuss this with the team. 

/cc @rrrene @moellenbeck

**Comment by ElRaptorus** [comment]
P.S.: 
It should be noted that the ProcessEngine keeps all results for each FlowNodeInstance stored in an internal Array. 

So no result is lost or overwritten. 

The problem here only occurs, when an attempt is made to create a TokenHistory in the old format (which, unfortunately, is still the format that is widely used with most ProcessModels).

**Comment by ElRaptorus** [comment]
@Vyperus I just tried to reproduce this, using the ProcessModel you provided.

I added a ScriptTask after the Join-Gateway, which prints out `token.history.UserTask1`. 

I ran the UserTask twice, once with selecting "abort" and once with "proceed". 

Since the UserTask will not be repeated, if you select "proceed", the expected form field value printed to the console for that UserTask will be "true".

And as you can see:
![Bildschirmfoto 2019-06-17 um 15 59 18](https://user-images.githubusercontent.com/15343316/59610124-05430900-9119-11e9-9e09-9e8d6bfb4d6c.png)

Just as I'd expect.

I used the most recent develop version for the ProcessEngine Runtime and the BPMN Studio.

Will try this with the master version as well, but as far as I can see, the token history is created as expected. 

If you continue to experience this issue, please let me know.

Here is the updated ProcessModel:
[token history.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3297318/token.history.bpmn.zip)
