### ISSUE TITLE
✨ When Using onEndEventReached Callback the EndEventId Always has to be Passed

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#376]
## Description

On the `startProcess()` Method of the ConsumerClient, its possible to set an `OnEndEventReachedCallback` parameter. This instructs the `startProcess()` method to resolve its given promise, when the EndEvent of the started process was reached.

If a Process only contains one StartEvent, its possible to omit the `startEventId` parameter. However, you always have to supply an `EndEventId`, even if the started Process only contains a single EndEvent.

## Possible solution

Do not force the user to supply an EndEventId if the started Process only contains one EndEvent when using the `OnProcessEnded` callback type.

**Comment by ElRaptorus** [comment]
Why don't you just use `onProcessInstanceFinished` then? 
This UseCase will resolve after the Process has finished, regardless of what EndEvent is reached. If you only have one EndEvent in your Process, then this is what you are looking for.

`onEndEventReached` is designed explicitly to wait for a specific EndEvent (like "I want to wait until my Process has reached the EndEvent ABC").
Using implicit magic here will render this UseCase pretty much useless. 

On the topic of implicit magic:
We decided some time ago that making the StartEventId optional was a bad idea as well, because it introduces implicit magic to the handling of ProcessInstances. 
The new `ProcessEngineClient` we are working on, as well as the `AtlasEngineClient` will require the user to pass a StartEventId again.
