### ISSUE TITLE
🐛Double onProcessError Message when using ErrorEndEvent

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#400]
## Description

Apparently the `onProcessError` callback gets called twice when the process runs into an ErrorEndEvent.

When subscribing on it and simply logging the messages you the following output:

<img width="926" alt="Bildschirmfoto 2019-09-10 um 11 42 21" src="https://user-images.githubusercontent.com/17248802/64603385-9e07be80-d3c0-11e9-891b-761eba72f7c8.png">

It seems like that the process is ending with an error (like an error in a ScriptTask) and a separate error event is thrown.
Also that second event seems not to be using the contract normally associated with the `ProcessErrorMessage`.

## Reproduction

- Run the following diagram
[TestDiagramm.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3594973/TestDiagramm.bpmn.zip)

## Possible solution

Only throw one error when running into the ErrorEndEvent.

**Comment by ElRaptorus** [comment]
@Vyperus 
These are actually two different types of notifications.

Take a closer look at the payloads you posted:

The first one contains `flowNodeInstanceId`, `flowNodeName` and `flowNodeId`. This is the message, specific for the `ProcessInstance`.

The second message is a _general_ message, which informs the user that a ProcessInstance has run into an error. Since this is a general message, no FlowNode information is contained in here.

These two messages are send across different event channels:
The first is send through `/processengine/process/:processInstanceId/error`
The second is send through `process_error`

Or did you received both messages through the same channel? Because _that_ would be an error. 🙂

**Comment by Vyperus** [comment]
@ElRaptorus 
I am just subscribing to `onProcessError` and getting both messages.

``` 
this.consumerClient.onProcessError(identity, <function-here>)
```

Is there something I am missing here? :)

**Comment by ElRaptorus** [comment]
> @ElRaptorus
> I am just subscribing to `onProcessError` and getting both messages.
> 
> ```
> this.consumerClient.onProcessError(identity, <function-here>)
> ```
> 
> Is there something I am missing here? :)

No, I think I just misunderstood you. 🙃 

The two messages are intended, but they are supposed to be send through different channels. That you get both through the same channel (`onProcessError`) is a bug.
