### ISSUE TITLE
🐛Error Boundary Event doesn't work as expected

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#408]
## Description

The Error Boundary Event doesn't "get used" when the ScriptTask it is attached to runs into an error.

![Bildschirmfoto 2019-09-13 um 11 24 32](https://user-images.githubusercontent.com/17248802/64852183-2da7aa00-d619-11e9-93e1-36a6e40fde97.png)

## Reproduction

- Run this Process
[ConfiguredFaultyProcess.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3609326/ConfiguredFaultyProcess.bpmn.zip)

## Possible solution

Handle syntax errors?
Use error boundary events correctly?

**Comment by Vyperus** [comment]
UPDATE:

This only happens if the Boundary Event is configures/contains an error. Possibly because there is some check happening here. However BPMN-Studio states that the Boundary Event HAS to be configured. (Error in Linter)

**Comment by Vyperus** [comment]
[ConfiguredFaultyProcess.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3609355/ConfiguredFaultyProcess.bpmn.zip)

This one works but show an error while modeling it.

**Comment by ElRaptorus** [comment]
@Vyperus 

> This only happens if the Boundary Event is configures/contains an error. 

If your intention is to write a BoundaryEvent that catches all errors, you can just "configure" an empty error (i.e. leave code, name and message empty).

Yes, this is somewhat annoying (especially since the ProcessEngine itself can actually handle ErrorBoundaryEvents without any configured error), but that's the way it is at the moment.

On a more general note:
- `name` is the name of the error **class** you want to match (like `NotFoundError`, `InternalServerError`, `SomeRandomCustomError` etc)
- `code` is a HTTP status code
- `message` is the actual message contained in the error

So if you encounter, say, an error like:
```
NotFoundError {
  code: 404,
  message: 'I did not find what you were looking for'
}
```

then the configured error would have one of the following to match (or a combination thereof):
`name` would be `NotFoundError`
`code` would be 404 and
`message` would be 'I did not find what you were looking for'

@alexanderkasten @SteffenKn @rrrene This should be added to the element's documentation, since this has caused confusion a number of times already.

**Comment by ElRaptorus** [comment]
Although, I just noted a funny glitch with the matching:

If the attached error definition has no "name" on it, then the other properties just get ignored.

We'll fix this.
