### ISSUE TITLE
🐛Unexpected state of process after stopping

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#474]
## Description

After stopping processes on 5Minds Portal the are usually in an unexpected state. 
They are still visible in Running Processes, but they have no active FlowNode in LET.

<img width="1312" alt="Bildschirmfoto 2019-11-25 um 14 09 56" src="https://user-images.githubusercontent.com/36449148/69543180-57703c00-0f8d-11ea-9d88-596a7e4e54d5.png">

<img width="727" alt="Bildschirmfoto 2019-11-25 um 14 10 18" src="https://user-images.githubusercontent.com/36449148/69543190-5d661d00-0f8d-11ea-8d0a-ddfe203f7b1b.png">

## Reproduction

Databases:
[process_engine_dbs.tar.gz](https://github.com/process-engine/process_engine_runtime/files/3886756/process_engine_dbs.tar.gz)

## My setup

ProcessEngineRuntime: 9.1.0
BPMN Studio: 5.9.0

**Comment by ElRaptorus** [comment]
After investigating this with @alexanderkasten and @roblen45 we think this might occur because the ProcessEngine is using the wrong identity when terminating the ProcessInstance.
It _should_ use the identity of the user that termianted the ProcessInstance, but instead, the _owner_ of the ProcessInstance is used.

It has yet to be confirmed that this is causing this issue, but at the moment this seems to be the most likely explanation.
