### ISSUE TITLE
God Token Warning is logged as an Error

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#484]
## Description

When the `allowGodToken` property is set to `true`, a warning is logged. This warning however is logged as an `error`. In my opinion its better to log this _warning_ as an actual _warning_ instead of an _error_. 

## Reproduction

* Set the `allowGodToken` property to `true`
* See, that the warning is logged as an `error` instead a warning.

**Comment by ElRaptorus** [comment]
This is intentional, because of the severity of this setting. 
In a production environment, you'd usually not want such tokens to be allowed, unless you're debugging something. 

Warnings have a habit of getting ignored, because, well, they're just warnings. The red stands out a lot more.
This way, the user knows that he has a setting that he should think twice of using.
