### ISSUE TITLE
♻️ Add a more "user friendly" message when the port for the HTTP extension is already in use

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#86]
#### Describe your issue

When the Port, where the runtime should listen is blocked by another application, the user only receives the default `stack trace`, since the thrown exception is not handled properly. 

```
throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

IMO this looks kinda "unfinish". We should catch the thrown exception and add a message for this case. 

#### How can others reproduce the issue?

* Start the runtime
* Try to start another run time which should listen on the same port
* Look at the console output

#### Possible solution

* Catch exception
* Print out a pretty message
* ???
* Profit

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@robpal94 

The question here is:
Does the BPMN Studio User receive these types of errors? 
If he doesn't, I'd be perfectly happy for the error messages to remain as they are, *because* they contain a stack trace.
Makes it far easier for us to locate errors if anything goes wrong during startup.

And there are actually tons of things that could go wrong (A Config is is missing, some config is invalid, port/adress are in use, database not reachable, etc) and most of these situations do not really produce comprehensive error messages, mostly because external components, like addict-ioc, lack comprehensive error logging.

Parsing all of these in the runtime would be real pain and in my mind not worth the effort.

If your issue is only with this message in particular and you actually *do* pass them to the BPMN studio user, you should catch and process this error in the Studio.

/cc @cmg-dev @5ebastianMeier @SteffenKn @alexanderkasten @Vyperus @roblen45

**Comment by ElRaptorus** [comment]
Since nobody even seems fit to comment here and I don't consider this to be a backend issue, I'm going to close this.
