### ISSUE TITLE
When saving user task a 422 error occours

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/process_engine_runtime#9]
#### Describe your issue

When saving a process with user task, a 422 (Unprocessable Entity) occurs

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
@dominikkaminski Can you provide the diagram in which this occurs? Or a small description of what you did to produce the error?

**Comment by ElRaptorus** [comment]
@dominikkaminski @Vyperus 
I think this might have been fixed by this PR:
https://github.com/process-engine/process_engine/pull/152

Dunno where the problem described in this issue was encountered, though, so I can't say for sure. 
@dominikkaminski Perhaps you could check again and provide a diagram, if the error persists?

**Comment by dominikkaminski** [comment]
With process-engine version 1.2.0 it is **not reproduceable**
